# -*- coding: utf-8 -*-

SCHEME = {
    '417776': {'name': '2019カレンダー', 'type': 'promotion'},
    '417784': {'name': '2019カレンダー卓上', 'type': 'promotion'},
    '429599': {'name': '2020カレンダー(卓上)', 'type': 'promotion'},
    '429581': {'name': '2020カレンダー(壁掛け)', 'type': 'promotion'},
    '900041': {'name': '9.2ブロウブラシ(大)', 'type': 'cosmetics'},
    '111': {'name': 'AFC会費', 'type': 'promotion'},
    '405961': {'name': 'AQSケース 135g用', 'type': 'promotion'},
    '424664': {'name': 'AQSポーチ', 'type': 'promotion'},
    '405979': {'name': 'ASQケース 70g用', 'type': 'promotion'},
    '900042': {'name': 'B-5ブロウブラシ(小)', 'type': 'cosmetics'},
    '732': {'name': 'EX シャンプ- リフィル', 'type': 'cosmetics'},
    '702': {'name': 'EX シャンプ―', 'type': 'cosmetics'},
    '429383': {'name': 'EX シャンプ―MS', 'type': 'promotion'},
    '703': {'name': 'EX トリートメント', 'type': 'cosmetics'},
    '410689': {'name': 'EXシャンプー ミニチュアサンプル', 'type': 'promotion'},
    '429391': {'name': 'EXトリートメントＭＳ', 'type': 'promotion'},
    '410697': {'name': 'EXトリートメント ミニチュアサンプル', 'type': 'promotion'},
    '577': {'name': 'MLFダークカラー', 'type': 'cosmetics'},
    '576': {'name': 'MLFハイライトカラー', 'type': 'cosmetics'},
    '410142': {'name': 'MSバッグ', 'type': 'promotion'},
    '701': {'name': 'N コンディショナー', 'type': 'cosmetics'},
    '731': {'name': 'N コンディショナー リフィル', 'type': 'cosmetics'},
    '429375': {'name': 'N コンディショナーMS', 'type': 'promotion'},
    '700': {'name': 'N シャンプ―', 'type': 'cosmetics'},
    '429367': {'name': 'N シャンプ―MS', 'type': 'promotion'},
    '730': {'name': 'N シャンプー リフィル', 'type': 'cosmetics'},
    '430471': {'name': 'NewヘアケアBC用', 'type': 'cosmetics'},
    '273607': {'name': 'NO.1 フェイスブラシ', 'type': 'promotion'},
    '273706': {'name': 'NO.2 チークブラシ', 'type': 'promotion'},
    '273805': {'name': 'NO.3 アイシャドーブラシ(大)', 'type': 'promotion'},
    '274001': {'name': 'NO.4 アイシャドーブラシ(中)', 'type': 'promotion'},
    '273904': {'name': 'NO.5 アイシャドーブラシ(小)', 'type': 'promotion'},
    '274100': {'name': 'NO.6 アイシャドーチップ', 'type': 'promotion'},
    '369117': {'name': 'No.6替えアイシャドーチップ(小)3個入', 'type': 'promotion'},
    '369133': {'name': 'No.6替えアイシャドーチップ(大)3個入', 'type': 'promotion'},
    '367971': {'name': 'No.7 眉ブラシ&コーム', 'type': 'promotion'},
    '274209': {'name': 'NO.8 リップブラシ', 'type': 'promotion'},
    '1715': {'name': 'No.アイシャドウブラシ(小)', 'type': 'promotion'},
    '1716': {'name': 'No6アイシャドウチップ', 'type': 'promotion'},
    '585': {'name': 'PF  115(オークルミディアム)', 'type': 'cosmetics'},
    '591': {'name': 'PF 111 リフィル(ピンクミディアム)', 'type': 'cosmetics'},
    '581': {'name': 'PF 111(ピンクミディアム)', 'type': 'cosmetics'},
    '592': {'name': 'PF 112 リフィル (ナチュラルライト)', 'type': 'cosmetics'},
    '582': {'name': 'PF 112(ナチュラルライト)', 'type': 'cosmetics'},
    '593': {'name': 'PF 113 リフィル(ナチュラル)', 'type': 'cosmetics'},
    '583': {'name': 'PF 113(ナチュラル)', 'type': 'cosmetics'},
    '594': {'name': 'PF 114 リフィル(オークルライト)', 'type': 'cosmetics'},
    '584': {'name': 'PF 114(オークルライト)', 'type': 'cosmetics'},
    '595': {'name': 'PF 115 リフィル (オークルミディアム)', 'type': 'cosmetics'},
    '1111': {'name': 'ppバック', 'type': 'promotion'},
    '369787': {'name': 'PPバック A', 'type': 'promotion'},
    '369795': {'name': 'PPバック B', 'type': 'promotion'},
    '381418': {'name': 'QSギフトボックス(ピンク)', 'type': 'promotion'},
    '14': {'name': 'SP(ラージ)', 'type': 'cosmetics'},
    '755': {'name': 'アイブロウ 550リフィル ブラウン', 'type': 'cosmetics'},
    '756': {'name': 'アイブロウ 560リフィル グレー', 'type': 'cosmetics'},
    '971': {'name': 'アイブロウパウダー', 'type': 'cosmetics'},
    '972': {'name': 'アイブロウパウダー リフィル', 'type': 'cosmetics'},
    '754': {'name': 'アイブロウホルダー', 'type': 'cosmetics'},
    '750': {'name': 'アイライナー 500(リフィル)ブラウン', 'type': 'cosmetics'},
    '751': {'name': 'アイライナー 510(リフィル)グレー', 'type': 'cosmetics'},
    '749': {'name': 'アイライナーホルダー', 'type': 'cosmetics'},
    '369125': {'name': 'アイラッシュカラー替えゴム', 'type': 'promotion'},
    '206': {'name': 'アピブラシ', 'type': 'cosmetics'},
    '614': {'name': 'アムニーAP スキンコート', 'type': 'cosmetics'},
    '611': {'name': 'アムニーAP スキンソープ', 'type': 'cosmetics'},
    '613': {'name': 'アムニーAP スキンローション', 'type': 'cosmetics'},
    '615': {'name': 'アムニーAP ボディソープ', 'type': 'cosmetics'},
    '30': {'name': 'アムニーM クリーン', 'type': 'cosmetics'},
    '31': {'name': 'アムニーM ローション', 'type': 'cosmetics'},
    '1120': {'name': 'アルソアクィーンシルバー', 'type': 'cosmetics'},
    '1': {'name': 'アルソアクイーンシルバー70g', 'type': 'cosmetics'},
    '421644': {'name': 'アルソアクィーンシルバーPF', 'type': 'cosmetics'},
    '2': {'name': 'アルソアクイーンシルバーPF 70g', 'type': 'cosmetics'},
    '20': {'name': 'アルソアクイーンシルバーリフィル', 'type': 'cosmetics'},
    '925': {'name': 'アルソアコンチェルト', 'type': 'cosmetics'},
    '606': {'name': 'イロンネ 育毛エッセンス', 'type': 'cosmetics'},
    '605': {'name': 'イロンネ 育毛ローション', 'type': 'cosmetics'},
    '1151': {'name': 'エス', 'type': 'cosmetics'},
    '1134': {'name': 'エッセンスI', 'type': 'cosmetics'},
    '1124': {'name': 'エッセンスII', 'type': 'cosmetics'},
    '421842': {'name': 'エッセンスIIMS', 'type': 'promotion'},
    '1154': {'name': 'エッセンスマスク', 'type': 'cosmetics'},
    '3352': {'name': 'カストマーズカード', 'type': 'promotion'},
    '374017': {'name': 'カストマーズカード', 'type': 'promotion'},
    '418807': {'name': 'カストマーズカードバインダー', 'type': 'promotion'},
    '3394': {'name': 'ギフトBOB(AQS)バラ売り', 'type': 'promotion'},
    '339409': {'name': 'ギフトBOX(AQS)', 'type': 'promotion'},
    '373051': {'name': 'クイーンシルバ ミニチュアサンプル', 'type': 'promotion'},
    '1101': {'name': 'クィーンシルバー70g', 'type': 'cosmetics'},
    '421975': {'name': 'クィーンシルバー70gケース', 'type': 'promotion'},
    '421793': {'name': 'クィーンシルバーPF MS', 'type': 'promotion'},
    '421967': {'name': 'クィーンシルバーケース135g', 'type': 'promotion'},
    '1130': {'name': 'クレイパック', 'type': 'cosmetics'},
    '421800': {'name': 'クレイパック MS', 'type': 'promotion'},
    '329806': {'name': 'コチャママ クックスター', 'type': 'promotion'},
    '399908': {'name': 'コチャママ スパピリカ', 'type': 'promotion'},
    '362210': {'name': 'コチャママクックアクアメイト', 'type': 'promotion'},
    '11': {'name': 'こちやママぽつと', 'type': 'promotion'},
    '3362': {'name': 'コミュニケーションシート', 'type': 'promotion'},
    '374025': {'name': 'コミュニケーションシート', 'type': 'promotion'},
    '422006': {'name': 'コンパクトミラー', 'type': 'promotion'},
    '24': {'name': 'サースレア エッセンス', 'type': 'cosmetics'},
    '22': {'name': 'サースレア クリーン', 'type': 'cosmetics'},
    '26': {'name': 'サースレア モイストベイス', 'type': 'cosmetics'},
    '21': {'name': 'サースレア ローション', 'type': 'cosmetics'},
    '239': {'name': 'サースレアローションBIG', 'type': 'cosmetics'},
    '221': {'name': 'シェードオン CN311(ローズウッド)', 'type': 'cosmetics'},
    '224': {'name': 'シェードオン CN314(ブルーデイジー)', 'type': 'cosmetics'},
    '231': {'name': 'シェードオン CN321(カカオブラウン)', 'type': 'cosmetics'},
    '234': {'name': 'シェードオン CN324(ディープインディゴ)', 'type': 'cosmetics'},
    '211': {'name': 'シェードオン N301(サクラフルール)', 'type': 'cosmetics'},
    '212': {'name': 'シェードオン N302(カサブランカ)', 'type': 'cosmetics'},
    '213': {'name': 'シェードオン N303(パーリーダリア)', 'type': 'cosmetics'},
    '214': {'name': 'シェードオン N304(サンフラワー)', 'type': 'cosmetics'},
    '215': {'name': 'シェードオン N305(ピンクスイートピー)', 'type': 'cosmetics'},
    '216': {'name': 'シェードオン N306(ダイアモンドリリー)', 'type': 'cosmetics'},
    '222': {'name': 'シェードオン N312(シルバーツリー)', 'type': 'cosmetics'},
    '225': {'name': 'シェードオン N315(ライラックパープル)', 'type': 'cosmetics'},
    '232': {'name': 'シェードオン N322(ブラックオリーブ)', 'type': 'cosmetics'},
    '235': {'name': 'シェードオン N325(パンジーバイオレット)', 'type': 'cosmetics'},
    '223': {'name': 'シェードオン NW313(サニーピーチ)', 'type': 'cosmetics'},
    '226': {'name': 'シェードオン NW316(ホリーゴールド)', 'type': 'cosmetics'},
    '227': {'name': 'シェードオン NW317(シナモンブラウン)', 'type': 'cosmetics'},
    '233': {'name': 'シェードオン NW323(シャイニーウッド)', 'type': 'cosmetics'},
    '236': {'name': 'シェードオン NW326(モスグリーン)', 'type': 'cosmetics'},
    '21000': {'name': 'シェードオンケース', 'type': 'promotion'},
    '94': {'name': 'ジオリナ ビエッセ (ラージ)', 'type': 'supplement'},
    '93': {'name': 'ジオリナ ビエッセ レギュラー', 'type': 'supplement'},
    '74': {'name': 'ジオリナ ピュアカル', 'type': 'supplement'},
    '95': {'name': 'ジオリナ リナカンC', 'type': 'supplement'},
    '85': {'name': 'ジオリナ 酵素', 'type': 'supplement'},
    '403965': {'name': 'ジオリナ 酵素G', 'type': 'supplement'},
    '87': {'name': 'ジオリナ 酵素プラス(ラージ)', 'type': 'supplement'},
    '86': {'name': 'ジオリナ 酵素プラス(レギュラー)', 'type': 'supplement'},
    '90': {'name': 'ジオリナ 白鶴霊芝 AG', 'type': 'supplement'},
    '92': {'name': 'ジオリナ 白鶴霊芝 EX(ラージ)', 'type': 'supplement'},
    '91': {'name': 'ジオリナ 白鶴霊芝 EX(レギュラー)', 'type': 'supplement'},
    '89': {'name': 'ジオリナ 霊芝 (ラージ)', 'type': 'supplement'},
    '88': {'name': 'ジオリナ 霊芝(レギュラー)', 'type': 'supplement'},
    '398950': {'name': 'シフターネット(LFP)', 'type': 'promotion'},
    '426876': {'name': 'ジュエリーポーチ', 'type': 'promotion'},
    '402644': {'name': 'ショッピングバックL', 'type': 'promotion'},
    '402652': {'name': 'ショッピングバックM', 'type': 'promotion'},
    '439': {'name': 'しらきぬの湯', 'type': 'cosmetics'},
    '425026': {'name': 'スーパーBCキット(セット)', 'type': 'cosmetics'},
    '406240': {'name': 'スキンケア紙芝居2014', 'type': 'promotion'},
    '425084': {'name': 'スキンケア紙芝居2019', 'type': 'promotion'},
    '51': {'name': 'スクワランオイル エス', 'type': 'cosmetics'},
    '390724': {'name': 'すこやかスタディ用紙芝居2011', 'type': 'promotion'},
    '156': {'name': 'セット3 I', 'type': 'cosmetics'},
    '157': {'name': 'セット3 II', 'type': 'cosmetics'},
    '158': {'name': 'セット3 セル', 'type': 'cosmetics'},
    '53': {'name': 'セルアクアマスク', 'type': 'cosmetics'},
    '1144': {'name': 'セルエッセンス', 'type': 'cosmetics'},
    '1153': {'name': 'セルジェル', 'type': 'cosmetics'},
    '52': {'name': 'セルジェル', 'type': 'cosmetics'},
    '1146': {'name': 'セルセラム', 'type': 'cosmetics'},
    '421868': {'name': 'セルセラムMS', 'type': 'promotion'},
    '1141': {'name': 'セルローション', 'type': 'cosmetics'},
    '421834': {'name': 'セルローション MS', 'type': 'promotion'},
    '406943': {'name': 'ソナディスクレイ', 'type': 'cosmetics'},
    '50': {'name': 'ソナディスポーテ エッセンス', 'type': 'cosmetics'},
    '49': {'name': 'ソナディスポーテ ローション', 'type': 'cosmetics'},
    '48': {'name': 'ソナディスボーテエモリエントクレイ', 'type': 'cosmetics'},
    '360497': {'name': 'ターバン(グレー)1枚', 'type': 'promotion'},
    '360496': {'name': 'ターバン(グレー)5枚入り', 'type': 'promotion'},
    '393969': {'name': 'ターバン(ピンク)1枚', 'type': 'promotion'},
    '393968': {'name': 'ターバン(ピンク)5枚入り', 'type': 'promotion'},
    '426800': {'name': 'ダイアリー2020 スカイブルー', 'type': 'promotion'},
    '426818': {'name': 'ダイアリー2020 ネイビー', 'type': 'promotion'},
    '426793': {'name': 'ダイアリー2020 レッド', 'type': 'promotion'},
    '373548': {'name': 'ダイヤリー', 'type': 'promotion'},
    '426884': {'name': 'ティッシュケース', 'type': 'promotion'},
    '2471': {'name': 'ティッシュペーパー', 'type': 'promotion'},
    '602': {'name': 'ティネ EXシャンプー', 'type': 'cosmetics'},
    '603': {'name': 'ティネ EXトリートメント', 'type': 'cosmetics'},
    '630': {'name': 'ティネ シャンプーRE', 'type': 'cosmetics'},
    '604': {'name': 'ティネ ヘアミスト', 'type': 'cosmetics'},
    '631': {'name': 'ティネ リンスRE', 'type': 'cosmetics'},
    '410663': {'name': 'ティネシャンプー ミニチュアサンプル', 'type': 'promotion'},
    '410671': {'name': 'ティネリンス ミニチュアサンプル', 'type': 'promotion'},
    '411520': {'name': 'デュアルブラシ', 'type': 'promotion'},
    '418758': {'name': 'トートバッグ', 'type': 'promotion'},
    '424961': {'name': 'トラベルキット(CELL)', 'type': 'promotion'},
    '424945': {'name': 'トラベルキット(I)', 'type': 'promotion'},
    '424953': {'name': 'トラベルキット(II)', 'type': 'promotion'},
    '6000': {'name': 'トリートメントオイル', 'type': 'cosmetics'},
    '705': {'name': 'トリートメントオイル', 'type': 'cosmetics'},
    '429408': {'name': 'トリートメントオイルMS', 'type': 'promotion'},
    '44': {'name': 'ヌクォル R セルエッセンス', 'type': 'cosmetics'},
    '42': {'name': 'ヌクォル R セルクレイ', 'type': 'cosmetics'},
    '46': {'name': 'ヌクォル R セルセラム', 'type': 'cosmetics'},
    '41': {'name': 'ヌクォル R セルローション', 'type': 'cosmetics'},
    '973': {'name': 'ハートコレクション💛シェードオン', 'type': 'cosmetics'},
    '974': {'name': 'ハートコレクション💛ロングマスカラ', 'type': 'cosmetics'},
    '412875': {'name': 'ハンカチ オレンジ', 'type': 'promotion'},
    '412891': {'name': 'ハンカチ ピンク', 'type': 'promotion'},
    '412883': {'name': 'ハンカチ レモン', 'type': 'promotion'},
    '412619': {'name': 'ハンディブラシセット', 'type': 'promotion'},
    '78': {'name': 'ビエッセEX ラージ', 'type': 'supplement'},
    '77': {'name': 'ビエッセEX(レギュラー)', 'type': 'supplement'},
    '11111': {'name': 'ビューラー', 'type': 'promotion'},
    '555': {'name': 'ファンデーションテスター', 'type': 'promotion'},
    '54': {'name': 'フェイシャルエッセンスマスク', 'type': 'cosmetics'},
    '359720': {'name': 'フェイシャルタオル', 'type': 'promotion'},
    '377574': {'name': 'フェイシャルマスク(10シート)', 'type': 'promotion'},
    '68': {'name': 'フェイスパウダー #', 'type': 'cosmetics'},
    '66': {'name': 'フェイスパウダー(リフィル#)', 'type': 'cosmetics'},
    '311': {'name': 'ブラッシュオン CN611(キューティーピンク', 'type': 'cosmetics'},
    '312': {'name': 'ブラッシュオン CN612(エレガントローズ)', 'type': 'cosmetics'},
    '313': {'name': 'ブラッシュオン N613(コーラルチャーミン', 'type': 'cosmetics'},
    '314': {'name': 'ブラッシュオン N614(ノーブルレッド)', 'type': 'cosmetics'},
    '315': {'name': 'ブラッシュオン NW615(グレイスオレンジ)', 'type': 'cosmetics'},
    '316': {'name': 'ブラッシュオン NW616(ハピネスオレンジ)', 'type': 'cosmetics'},
    '321': {'name': 'ブラッシュオン シャイン621(シアーピンク)', 'type': 'cosmetics'},
    '5555': {'name': 'ブラッシュオンケース', 'type': 'promotion'},
    '322': {'name': 'ブラッシュオンシャイン 622(ピュアホワイト', 'type': 'cosmetics'},
    '323': {'name': 'ブラッシュオンシャイン 623', 'type': 'cosmetics'},
    '438': {'name': 'プリシーノ バスパウダー', 'type': 'cosmetics'},
    '607': {'name': 'プリシーノ ボディソープ', 'type': 'cosmetics'},
    '608': {'name': 'プリシーノ ボディソープ(リフィル)', 'type': 'cosmetics'},
    '609': {'name': 'プリシーノ ボディミスト', 'type': 'cosmetics'},
    '444': {'name': 'プレジールベージュ リップスティック', 'type': 'cosmetics'},
    '350368': {'name': 'プレペアローション ミニチュアサンプル', 'type': 'promotion'},
    '274308': {'name': 'プロ用 メイクアップブラシケース', 'type': 'promotion'},
    '431700': {'name': 'ヘアケア紙芝居', 'type': 'promotion'},
    '421991': {'name': 'ヘアブラシ', 'type': 'promotion'},
    '704': {'name': 'ヘアミスト', 'type': 'cosmetics'},
    '402660': {'name': 'ペーパーバックL', 'type': 'promotion'},
    '402678': {'name': 'ペーパーバックM', 'type': 'promotion'},
    '916': {'name': 'ベスト4アルソアセットCELL', 'type': 'cosmetics'},
    '914': {'name': 'ベスト4アルソアセットI', 'type': 'cosmetics'},
    '915': {'name': 'ベスト4アルソアセットII', 'type': 'cosmetics'},
    '919': {'name': 'ベスト4セルローション', 'type': 'cosmetics'},
    '917': {'name': 'ベスト4ローションI', 'type': 'cosmetics'},
    '918': {'name': 'ベスト4ローションII', 'type': 'cosmetics'},
    '421412': {'name': 'ポケットダイアリー(レッド)', 'type': 'promotion'},
    '421420': {'name': 'ポケットダイヤリー(ブルー)', 'type': 'promotion'},
    '435794': {'name': 'マスクケース ハナ', 'type': 'promotion'},
    '435819': {'name': 'マスクケース モコアワ', 'type': 'promotion'},
    '404749': {'name': 'ミニチュアサンプル AQS', 'type': 'promotion'},
    '387101': {'name': 'ミニチュアサンプル アムニーAPスキンコート', 'type': 'promotion'},
    '404830': {'name': 'ミニチュアサンプル ソナディスボーテ エッセンス', 'type': 'promotion'},
    '404822': {'name': 'ミニチュアサンプル ソナディスボーテ ローション', 'type': 'promotion'},
    '387367': {'name': 'ミニチュアサンプル メイクオフ', 'type': 'promotion'},
    '404848': {'name': 'ミニチュアサンプル モイシュチュアージェル', 'type': 'promotion'},
    '387359': {'name': 'ミニチュアサンプル モイストメイクアップベース', 'type': 'promotion'},
    '402488': {'name': 'ミニチュアサンプル リベストプレペアローション', 'type': 'promotion'},
    '430124': {'name': 'ミニヘアブラシ', 'type': 'promotion'},
    '273508': {'name': 'メイクアップブラシセット', 'type': 'promotion'},
    '1731': {'name': 'メイクバック用パレット【PF】', 'type': 'promotion'},
    '1728': {'name': 'メイクバック用パレット【シェードオン】', 'type': 'promotion'},
    '1729': {'name': 'メイクバック用パレット【ブラッシュオン】', 'type': 'promotion'},
    '1730': {'name': 'メイクバック用パレット【リップカラー】', 'type': 'promotion'},
    '1155': {'name': 'モイスチャージェル', 'type': 'cosmetics'},
    '55': {'name': 'モイスチャージェル', 'type': 'cosmetics'},
    '421876': {'name': 'モイスチャージェルMS', 'type': 'promotion'},
    '1126': {'name': 'モイストベイス', 'type': 'cosmetics'},
    '40806': {'name': 'モイストベイス ミニチュアサンプル', 'type': 'promotion'},
    '421850': {'name': 'モイストベイスMS', 'type': 'promotion'},
    '414235': {'name': 'モイストメイクアップベースMS', 'type': 'promotion'},
    '424135': {'name': 'モイストメイクアップベースMS', 'type': 'promotion'},
    '412247': {'name': 'モイストリキッドファンデテスタ', 'type': 'promotion'},
    '72': {'name': 'ライフォリジン Fe', 'type': 'supplement'},
    '76': {'name': 'ライフォリジン オメガ3', 'type': 'supplement'},
    '75': {'name': 'ライフォリジン クリア', 'type': 'supplement'},
    '73': {'name': 'ライフォリジン ミネラル', 'type': 'supplement'},
    '571': {'name': 'リキッドファンデーション 101(ピンクミディ', 'type': 'cosmetics'},
    '572': {'name': 'リキッドファンデーション 102(ナチュラルラ', 'type': 'cosmetics'},
    '573': {'name': 'リキッドファンデーション 103(ナチュラル)', 'type': 'cosmetics'},
    '574': {'name': 'リキッドファンデーション 104(オークルライ', 'type': 'cosmetics'},
    '575': {'name': 'リキッドファンデーション 105(オークルミデ', 'type': 'cosmetics'},
    '421': {'name': 'リップカラー 821(フローズンアイス)', 'type': 'cosmetics'},
    '422': {'name': 'リップカラー 822(シャンパーニュ)', 'type': 'cosmetics'},
    '383': {'name': 'リップカラー 83', 'type': 'cosmetics'},
    '401': {'name': 'リップカラー CN801(マカロンピンク)', 'type': 'cosmetics'},
    '402': {'name': 'リップカラー CN802(ストロベリーモーブ)', 'type': 'cosmetics'},
    '403': {'name': 'リップカラー CN803(ローズジャム)', 'type': 'cosmetics'},
    '404': {'name': 'リップカラー CN804(ブラックカシス)', 'type': 'cosmetics'},
    '405': {'name': 'リップカラー N805(ジェリービーンズ)', 'type': 'cosmetics'},
    '406': {'name': 'リップカラー N806(ラズベリーレッド)', 'type': 'cosmetics'},
    '407': {'name': 'リップカラー N807(ワインレッド)', 'type': 'cosmetics'},
    '408': {'name': 'リップカラー NW808(ピンクグレープフル', 'type': 'cosmetics'},
    '409': {'name': 'リップカラー NW809(ピーナッツクリーム)', 'type': 'cosmetics'},
    '410': {'name': 'リップカラー NW810(アプリコット)', 'type': 'cosmetics'},
    '411': {'name': 'リップカラー NW811(フランボワーズショコ', 'type': 'cosmetics'},
    '431': {'name': 'リップグロス 901(スターダストジュレ)', 'type': 'cosmetics'},
    '432': {'name': 'リップグロス 902(カクテルピンク)', 'type': 'cosmetics'},
    '433': {'name': 'リップグロス 903(オレンジドロップ)', 'type': 'cosmetics'},
    '40004': {'name': 'リップケース', 'type': 'promotion'},
    '65': {'name': 'リップコート', 'type': 'cosmetics'},
    '931': {'name': 'リップステイクオレンジ', 'type': 'cosmetics'},
    '932': {'name': 'リップステイクロース ゙', 'type': 'cosmetics'},
    '970': {'name': 'リップライナー(DeepRed)', 'type': 'cosmetics'},
    '371435': {'name': 'リナカンC', 'type': 'supplement'},
    '80': {'name': 'リナカン茶D', 'type': 'supplement'},
    '1080': {'name': 'リナカン茶Ð添付', 'type': 'supplement'},
    '81': {'name': 'リナカン茶W', 'type': 'supplement'},
    '1081': {'name': 'リナカン茶W添付', 'type': 'supplement'},
    '69': {'name': 'リベスト プレストパウダーS', 'type': 'cosmetics'},
    '70': {'name': 'リベスト プレストパウダーS リフィル', 'type': 'cosmetics'},
    '6': {'name': 'リベスト メイクオフ', 'type': 'cosmetics'},
    '15': {'name': 'リベスト モイストメイクアップベース', 'type': 'cosmetics'},
    '13': {'name': 'リベストSPプレぺアローション', 'type': 'cosmetics'},
    '389967': {'name': 'リベストアイラッシュカーラー', 'type': 'promotion'},
    '112': {'name': 'リベストスポンジパフケース付', 'type': 'cosmetics'},
    '753': {'name': 'リベストナチュラルロングマスカラ', 'type': 'cosmetics'},
    '12': {'name': 'リベストプレぺアロ-ション', 'type': 'cosmetics'},
    '5': {'name': 'リベストマスカラ', 'type': 'cosmetics'},
    '386806': {'name': 'リベストメイクカラーハーモニーケース', 'type': 'promotion'},
    '578': {'name': 'リベストモイストリキッドF 121', 'type': 'cosmetics'},
    '579': {'name': 'リベストモイストリキッドF 122', 'type': 'cosmetics'},
    '580': {'name': 'リベストモイストリキッドF 123', 'type': 'cosmetics'},
    '746': {'name': 'リベストリキッドアイライナー', 'type': 'cosmetics'},
    '113': {'name': 'リベスト替えスポンジ', 'type': 'cosmetics'},
    '71': {'name': 'リベスト替えパフ(LP)', 'type': 'cosmetics'},
    '159': {'name': 'リボーンI', 'type': 'cosmetics'},
    '161': {'name': 'リボーンキットCELL', 'type': 'cosmetics'},
    '160': {'name': 'リボーンキットII', 'type': 'cosmetics'},
    '1131': {'name': 'ローションI', 'type': 'cosmetics'},
    '421818': {'name': 'ローションI MS', 'type': 'promotion'},
    '1121': {'name': 'ローションII', 'type': 'cosmetics'},
    '421826': {'name': 'ローションII MS', 'type': 'promotion'},
    '412164': {'name': '健食ケース', 'type': 'promotion'},
    '1086': {'name': '酵素キャップ', 'type': 'promotion'},
    '1085': {'name': '酵素ミニ(添付)', 'type': 'promotion'},
    '397382': {'name': '私のお仕事カード', 'type': 'promotion'},
    '400135': {'name': '色番シール4個セット', 'type': 'promotion'},
    '313047': {'name': '真央クイーンシルバー 30g', 'type': 'cosmetics'},
    '454': {'name': '清流', 'type': 'cosmetics'},
    '425183': {'name': '総合カタログ', 'type': 'promotion'},
    '900': {'name': '送料', 'type': 'promotion'},
    '686': {'name': '替えアイシャドーチップ', 'type': 'cosmetics'},
    '687': {'name': '替えアイシャドーブラシ', 'type': 'cosmetics'},
    '99': {'name': '替えコットンパフ', 'type': 'cosmetics'},
    '688': {'name': '替えチークブラシ', 'type': 'cosmetics'},
    '692': {'name': '替えリップブラシ', 'type': 'cosmetics'},
    '426123': {'name': '年賀状2020', 'type': 'promotion'},
    '2140': {'name': '納品・領収書', 'type': 'promotion'},
    '429424': {'name': '納品領収書', 'type': 'promotion'},
    '390873': {'name': '販促品 アプローチブック 2011', 'type': 'promotion'},
    '402610': {'name': '販促品 カストマーズバインダー', 'type': 'promotion'},
    '690': {'name': '眉フラシ&コーム', 'type': 'cosmetics'},
    '392506': {'name': '美顔タオル(ピンク)', 'type': 'promotion'},
    '2000': {'name': '美顔タオルバラ', 'type': 'promotion'},
    '431172': {'name': '保冷バッグ', 'type': 'promotion'},
    '389959': {'name': '泡立てネット', 'type': 'promotion'},
    '402917': {'name': '泡立てボウル', 'type': 'promotion'},
    '2467': {'name': '名刺台紙', 'type': 'promotion'},
    '432089': {'name': 'アルソアカレンダー2021(壁掛け', 'type': 'promotion'},
    '432097': {'name': '2021カレンダー卓上', 'type': 'promotion'},
    '434910': {'name': 'ダイアリー2021(パープル)', 'type': 'promotion'},
    '434902': {'name': 'ダイアリー2021(ネイビー)', 'type': 'promotion'},
    '434944': {'name': '年賀状2021', 'type': 'promotion'},
    '435942': {'name': '柔らかハンカチタオル(ピンク)', 'type': 'promotion'},
    '435950': {'name': '柔らかハンカチタオル(サックスブル', 'type': 'promotion'},
    '430': {'name': 'リベストリップコート(NEW)', 'type': 'cosmetics'},
    '975': {'name': 'アルソアポイントファンデーション', 'type': 'cosmetics'},
    '16': {'name': 'SPプレペアNEW', 'type': 'cosmetics'},
    '437360': {'name': 'アルソア エム―スキット', 'type': 'promotion'},
    '273201': {'name': '眉カットハサミ', 'type': 'promotion'},
    '600': {'name': 'スカルプローション', 'type': 'cosmetics'},
    '601': {'name': 'スカルプエッセンス', 'type': 'cosmetics'},
    '4001': {'name': 'アルソア リップスティックPINK', 'type': 'cosmetics'},
    '4002': {'name': 'アルソア リップスティックRED', 'type': 'cosmetics'},
    '440595': {'name': '2022アルソアカレンダー(壁掛け)', 'type': 'promotion'},
    '440602': {'name': '2022アルソアカレンダー(卓上)', 'type': 'promotion'},
    '440230': {'name': 'ダイアリー(オレンジ)', 'type': 'promotion'},
    '440256': {'name': 'ダイアリー(ブラウン)', 'type': 'promotion'},
    '421347': {'name': 'ハンカチタオル(さくら)', 'type': 'promotion'},
    '421355': {'name': 'ハンカチタオル(アイリス)', 'type': 'promotion'},
    '82': {'name': '白鶴霊芝ティ', 'type': 'supplement'},
    '96': {'name': 'ライフォリジンミネラル', 'type': 'supplement'},
    '97': {'name': 'ライフォリジンオメガ3', 'type': 'supplement'},
}
